### ISSUE TITLE
s3_copy_object.py uses preserve_metadata but should be preserve_acl

### ISSUE THREAD

**Issue by garnaat** [garnaat/paws#2]
The copy_object function defines a parameter called preserve_metadata but later the function refers to preserve_acl.

**Comment by ahamilton55** [comment]
Not sure if it is totally correct yet. You still never define preserve_acl. Currently you have:

```
def copy_object(src_bucket_name,
    src_key_name,
    dst_bucket_name,
    dst_key_name,
    preserve_metadata=True):
```

But I believe that you want to add `preserve_acl=True` to this as well:

```
def copy_object(src_bucket_name,
    src_key_name,
    dst_bucket_name,
    dst_key_name,
    preserve_metadata=True,
    preserve_acl=True):
```

**Comment by garnaat** [comment]
Oh, fine Andrew.  Just ruin my day, why don't you 8^)

Actually, what I meant to do was change preserve_metadata to preserve_acl.  I did that in the docstring but not in the actual code and in my experience it's much more effective if you make the change in the code rather than the comments.

Having thought about it a bit, though, it's probably good to have both params available so I'll check in a new version shortly that will (hopefully) do just that.
